// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: campaign.proto
// Protobuf Java Version: 4.27.2

package com.example.campaign.protos;

/**
 * Protobuf type {@code campaign.Campaign}
 */
public final class Campaign extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:campaign.Campaign)
    CampaignOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Campaign.class.getName());
  }
  // Use Campaign.newBuilder() to construct.
  private Campaign(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Campaign() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.campaign.protos.CampaignProtos.internal_static_campaign_Campaign_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.campaign.protos.CampaignProtos.internal_static_campaign_Campaign_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.campaign.protos.Campaign.class, com.example.campaign.protos.Campaign.Builder.class);
  }

  private int bitField0_;
  public static final int RULE_FIELD_NUMBER = 1;
  private com.example.campaign.protos.Rule rule_;
  /**
   * <code>.campaign.Rule rule = 1;</code>
   * @return Whether the rule field is set.
   */
  @java.lang.Override
  public boolean hasRule() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.campaign.Rule rule = 1;</code>
   * @return The rule.
   */
  @java.lang.Override
  public com.example.campaign.protos.Rule getRule() {
    return rule_ == null ? com.example.campaign.protos.Rule.getDefaultInstance() : rule_;
  }
  /**
   * <code>.campaign.Rule rule = 1;</code>
   */
  @java.lang.Override
  public com.example.campaign.protos.RuleOrBuilder getRuleOrBuilder() {
    return rule_ == null ? com.example.campaign.protos.Rule.getDefaultInstance() : rule_;
  }

  public static final int SCHEDULE_FIELD_NUMBER = 2;
  private com.example.campaign.protos.Schedule schedule_;
  /**
   * <code>.campaign.Schedule schedule = 2;</code>
   * @return Whether the schedule field is set.
   */
  @java.lang.Override
  public boolean hasSchedule() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.campaign.Schedule schedule = 2;</code>
   * @return The schedule.
   */
  @java.lang.Override
  public com.example.campaign.protos.Schedule getSchedule() {
    return schedule_ == null ? com.example.campaign.protos.Schedule.getDefaultInstance() : schedule_;
  }
  /**
   * <code>.campaign.Schedule schedule = 2;</code>
   */
  @java.lang.Override
  public com.example.campaign.protos.ScheduleOrBuilder getScheduleOrBuilder() {
    return schedule_ == null ? com.example.campaign.protos.Schedule.getDefaultInstance() : schedule_;
  }

  public static final int TARGET_FIELD_NUMBER = 3;
  private com.example.campaign.protos.Target target_;
  /**
   * <code>.campaign.Target target = 3;</code>
   * @return Whether the target field is set.
   */
  @java.lang.Override
  public boolean hasTarget() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.campaign.Target target = 3;</code>
   * @return The target.
   */
  @java.lang.Override
  public com.example.campaign.protos.Target getTarget() {
    return target_ == null ? com.example.campaign.protos.Target.getDefaultInstance() : target_;
  }
  /**
   * <code>.campaign.Target target = 3;</code>
   */
  @java.lang.Override
  public com.example.campaign.protos.TargetOrBuilder getTargetOrBuilder() {
    return target_ == null ? com.example.campaign.protos.Target.getDefaultInstance() : target_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getRule());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getSchedule());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getTarget());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRule());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSchedule());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTarget());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.campaign.protos.Campaign)) {
      return super.equals(obj);
    }
    com.example.campaign.protos.Campaign other = (com.example.campaign.protos.Campaign) obj;

    if (hasRule() != other.hasRule()) return false;
    if (hasRule()) {
      if (!getRule()
          .equals(other.getRule())) return false;
    }
    if (hasSchedule() != other.hasSchedule()) return false;
    if (hasSchedule()) {
      if (!getSchedule()
          .equals(other.getSchedule())) return false;
    }
    if (hasTarget() != other.hasTarget()) return false;
    if (hasTarget()) {
      if (!getTarget()
          .equals(other.getTarget())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRule()) {
      hash = (37 * hash) + RULE_FIELD_NUMBER;
      hash = (53 * hash) + getRule().hashCode();
    }
    if (hasSchedule()) {
      hash = (37 * hash) + SCHEDULE_FIELD_NUMBER;
      hash = (53 * hash) + getSchedule().hashCode();
    }
    if (hasTarget()) {
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTarget().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.campaign.protos.Campaign parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.campaign.protos.Campaign parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.campaign.protos.Campaign parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.campaign.protos.Campaign parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.campaign.protos.Campaign parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.campaign.protos.Campaign parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.campaign.protos.Campaign parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.campaign.protos.Campaign parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.campaign.protos.Campaign parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.campaign.protos.Campaign parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.campaign.protos.Campaign parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.campaign.protos.Campaign parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.campaign.protos.Campaign prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code campaign.Campaign}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:campaign.Campaign)
      com.example.campaign.protos.CampaignOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.campaign.protos.CampaignProtos.internal_static_campaign_Campaign_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.campaign.protos.CampaignProtos.internal_static_campaign_Campaign_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.campaign.protos.Campaign.class, com.example.campaign.protos.Campaign.Builder.class);
    }

    // Construct using com.example.campaign.protos.Campaign.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getRuleFieldBuilder();
        getScheduleFieldBuilder();
        getTargetFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rule_ = null;
      if (ruleBuilder_ != null) {
        ruleBuilder_.dispose();
        ruleBuilder_ = null;
      }
      schedule_ = null;
      if (scheduleBuilder_ != null) {
        scheduleBuilder_.dispose();
        scheduleBuilder_ = null;
      }
      target_ = null;
      if (targetBuilder_ != null) {
        targetBuilder_.dispose();
        targetBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.campaign.protos.CampaignProtos.internal_static_campaign_Campaign_descriptor;
    }

    @java.lang.Override
    public com.example.campaign.protos.Campaign getDefaultInstanceForType() {
      return com.example.campaign.protos.Campaign.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.campaign.protos.Campaign build() {
      com.example.campaign.protos.Campaign result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.campaign.protos.Campaign buildPartial() {
      com.example.campaign.protos.Campaign result = new com.example.campaign.protos.Campaign(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.campaign.protos.Campaign result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rule_ = ruleBuilder_ == null
            ? rule_
            : ruleBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.schedule_ = scheduleBuilder_ == null
            ? schedule_
            : scheduleBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.target_ = targetBuilder_ == null
            ? target_
            : targetBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.campaign.protos.Campaign) {
        return mergeFrom((com.example.campaign.protos.Campaign)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.campaign.protos.Campaign other) {
      if (other == com.example.campaign.protos.Campaign.getDefaultInstance()) return this;
      if (other.hasRule()) {
        mergeRule(other.getRule());
      }
      if (other.hasSchedule()) {
        mergeSchedule(other.getSchedule());
      }
      if (other.hasTarget()) {
        mergeTarget(other.getTarget());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getRuleFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getScheduleFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getTargetFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.example.campaign.protos.Rule rule_;
    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.Rule, com.example.campaign.protos.Rule.Builder, com.example.campaign.protos.RuleOrBuilder> ruleBuilder_;
    /**
     * <code>.campaign.Rule rule = 1;</code>
     * @return Whether the rule field is set.
     */
    public boolean hasRule() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.campaign.Rule rule = 1;</code>
     * @return The rule.
     */
    public com.example.campaign.protos.Rule getRule() {
      if (ruleBuilder_ == null) {
        return rule_ == null ? com.example.campaign.protos.Rule.getDefaultInstance() : rule_;
      } else {
        return ruleBuilder_.getMessage();
      }
    }
    /**
     * <code>.campaign.Rule rule = 1;</code>
     */
    public Builder setRule(com.example.campaign.protos.Rule value) {
      if (ruleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rule_ = value;
      } else {
        ruleBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.Rule rule = 1;</code>
     */
    public Builder setRule(
        com.example.campaign.protos.Rule.Builder builderForValue) {
      if (ruleBuilder_ == null) {
        rule_ = builderForValue.build();
      } else {
        ruleBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.Rule rule = 1;</code>
     */
    public Builder mergeRule(com.example.campaign.protos.Rule value) {
      if (ruleBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          rule_ != null &&
          rule_ != com.example.campaign.protos.Rule.getDefaultInstance()) {
          getRuleBuilder().mergeFrom(value);
        } else {
          rule_ = value;
        }
      } else {
        ruleBuilder_.mergeFrom(value);
      }
      if (rule_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.campaign.Rule rule = 1;</code>
     */
    public Builder clearRule() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rule_ = null;
      if (ruleBuilder_ != null) {
        ruleBuilder_.dispose();
        ruleBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.Rule rule = 1;</code>
     */
    public com.example.campaign.protos.Rule.Builder getRuleBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getRuleFieldBuilder().getBuilder();
    }
    /**
     * <code>.campaign.Rule rule = 1;</code>
     */
    public com.example.campaign.protos.RuleOrBuilder getRuleOrBuilder() {
      if (ruleBuilder_ != null) {
        return ruleBuilder_.getMessageOrBuilder();
      } else {
        return rule_ == null ?
            com.example.campaign.protos.Rule.getDefaultInstance() : rule_;
      }
    }
    /**
     * <code>.campaign.Rule rule = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.Rule, com.example.campaign.protos.Rule.Builder, com.example.campaign.protos.RuleOrBuilder> 
        getRuleFieldBuilder() {
      if (ruleBuilder_ == null) {
        ruleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.campaign.protos.Rule, com.example.campaign.protos.Rule.Builder, com.example.campaign.protos.RuleOrBuilder>(
                getRule(),
                getParentForChildren(),
                isClean());
        rule_ = null;
      }
      return ruleBuilder_;
    }

    private com.example.campaign.protos.Schedule schedule_;
    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.Schedule, com.example.campaign.protos.Schedule.Builder, com.example.campaign.protos.ScheduleOrBuilder> scheduleBuilder_;
    /**
     * <code>.campaign.Schedule schedule = 2;</code>
     * @return Whether the schedule field is set.
     */
    public boolean hasSchedule() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.campaign.Schedule schedule = 2;</code>
     * @return The schedule.
     */
    public com.example.campaign.protos.Schedule getSchedule() {
      if (scheduleBuilder_ == null) {
        return schedule_ == null ? com.example.campaign.protos.Schedule.getDefaultInstance() : schedule_;
      } else {
        return scheduleBuilder_.getMessage();
      }
    }
    /**
     * <code>.campaign.Schedule schedule = 2;</code>
     */
    public Builder setSchedule(com.example.campaign.protos.Schedule value) {
      if (scheduleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        schedule_ = value;
      } else {
        scheduleBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.Schedule schedule = 2;</code>
     */
    public Builder setSchedule(
        com.example.campaign.protos.Schedule.Builder builderForValue) {
      if (scheduleBuilder_ == null) {
        schedule_ = builderForValue.build();
      } else {
        scheduleBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.Schedule schedule = 2;</code>
     */
    public Builder mergeSchedule(com.example.campaign.protos.Schedule value) {
      if (scheduleBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          schedule_ != null &&
          schedule_ != com.example.campaign.protos.Schedule.getDefaultInstance()) {
          getScheduleBuilder().mergeFrom(value);
        } else {
          schedule_ = value;
        }
      } else {
        scheduleBuilder_.mergeFrom(value);
      }
      if (schedule_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.campaign.Schedule schedule = 2;</code>
     */
    public Builder clearSchedule() {
      bitField0_ = (bitField0_ & ~0x00000002);
      schedule_ = null;
      if (scheduleBuilder_ != null) {
        scheduleBuilder_.dispose();
        scheduleBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.Schedule schedule = 2;</code>
     */
    public com.example.campaign.protos.Schedule.Builder getScheduleBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getScheduleFieldBuilder().getBuilder();
    }
    /**
     * <code>.campaign.Schedule schedule = 2;</code>
     */
    public com.example.campaign.protos.ScheduleOrBuilder getScheduleOrBuilder() {
      if (scheduleBuilder_ != null) {
        return scheduleBuilder_.getMessageOrBuilder();
      } else {
        return schedule_ == null ?
            com.example.campaign.protos.Schedule.getDefaultInstance() : schedule_;
      }
    }
    /**
     * <code>.campaign.Schedule schedule = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.Schedule, com.example.campaign.protos.Schedule.Builder, com.example.campaign.protos.ScheduleOrBuilder> 
        getScheduleFieldBuilder() {
      if (scheduleBuilder_ == null) {
        scheduleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.campaign.protos.Schedule, com.example.campaign.protos.Schedule.Builder, com.example.campaign.protos.ScheduleOrBuilder>(
                getSchedule(),
                getParentForChildren(),
                isClean());
        schedule_ = null;
      }
      return scheduleBuilder_;
    }

    private com.example.campaign.protos.Target target_;
    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.Target, com.example.campaign.protos.Target.Builder, com.example.campaign.protos.TargetOrBuilder> targetBuilder_;
    /**
     * <code>.campaign.Target target = 3;</code>
     * @return Whether the target field is set.
     */
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.campaign.Target target = 3;</code>
     * @return The target.
     */
    public com.example.campaign.protos.Target getTarget() {
      if (targetBuilder_ == null) {
        return target_ == null ? com.example.campaign.protos.Target.getDefaultInstance() : target_;
      } else {
        return targetBuilder_.getMessage();
      }
    }
    /**
     * <code>.campaign.Target target = 3;</code>
     */
    public Builder setTarget(com.example.campaign.protos.Target value) {
      if (targetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        target_ = value;
      } else {
        targetBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.Target target = 3;</code>
     */
    public Builder setTarget(
        com.example.campaign.protos.Target.Builder builderForValue) {
      if (targetBuilder_ == null) {
        target_ = builderForValue.build();
      } else {
        targetBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.Target target = 3;</code>
     */
    public Builder mergeTarget(com.example.campaign.protos.Target value) {
      if (targetBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          target_ != null &&
          target_ != com.example.campaign.protos.Target.getDefaultInstance()) {
          getTargetBuilder().mergeFrom(value);
        } else {
          target_ = value;
        }
      } else {
        targetBuilder_.mergeFrom(value);
      }
      if (target_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.campaign.Target target = 3;</code>
     */
    public Builder clearTarget() {
      bitField0_ = (bitField0_ & ~0x00000004);
      target_ = null;
      if (targetBuilder_ != null) {
        targetBuilder_.dispose();
        targetBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.Target target = 3;</code>
     */
    public com.example.campaign.protos.Target.Builder getTargetBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getTargetFieldBuilder().getBuilder();
    }
    /**
     * <code>.campaign.Target target = 3;</code>
     */
    public com.example.campaign.protos.TargetOrBuilder getTargetOrBuilder() {
      if (targetBuilder_ != null) {
        return targetBuilder_.getMessageOrBuilder();
      } else {
        return target_ == null ?
            com.example.campaign.protos.Target.getDefaultInstance() : target_;
      }
    }
    /**
     * <code>.campaign.Target target = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.Target, com.example.campaign.protos.Target.Builder, com.example.campaign.protos.TargetOrBuilder> 
        getTargetFieldBuilder() {
      if (targetBuilder_ == null) {
        targetBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.campaign.protos.Target, com.example.campaign.protos.Target.Builder, com.example.campaign.protos.TargetOrBuilder>(
                getTarget(),
                getParentForChildren(),
                isClean());
        target_ = null;
      }
      return targetBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:campaign.Campaign)
  }

  // @@protoc_insertion_point(class_scope:campaign.Campaign)
  private static final com.example.campaign.protos.Campaign DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.campaign.protos.Campaign();
  }

  public static com.example.campaign.protos.Campaign getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Campaign>
      PARSER = new com.google.protobuf.AbstractParser<Campaign>() {
    @java.lang.Override
    public Campaign parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Campaign> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Campaign> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.campaign.protos.Campaign getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

