// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: campaign.proto
// Protobuf Java Version: 4.27.2

package com.example.campaign.protos;

public interface CampaignOrBuilder extends
    // @@protoc_insertion_point(interface_extends:campaign.Campaign)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.campaign.Rule rule = 1;</code>
   * @return Whether the rule field is set.
   */
  boolean hasRule();
  /**
   * <code>.campaign.Rule rule = 1;</code>
   * @return The rule.
   */
  com.example.campaign.protos.Rule getRule();
  /**
   * <code>.campaign.Rule rule = 1;</code>
   */
  com.example.campaign.protos.RuleOrBuilder getRuleOrBuilder();

  /**
   * <code>.campaign.Schedule schedule = 2;</code>
   * @return Whether the schedule field is set.
   */
  boolean hasSchedule();
  /**
   * <code>.campaign.Schedule schedule = 2;</code>
   * @return The schedule.
   */
  com.example.campaign.protos.Schedule getSchedule();
  /**
   * <code>.campaign.Schedule schedule = 2;</code>
   */
  com.example.campaign.protos.ScheduleOrBuilder getScheduleOrBuilder();

  /**
   * <code>.campaign.Target target = 3;</code>
   * @return Whether the target field is set.
   */
  boolean hasTarget();
  /**
   * <code>.campaign.Target target = 3;</code>
   * @return The target.
   */
  com.example.campaign.protos.Target getTarget();
  /**
   * <code>.campaign.Target target = 3;</code>
   */
  com.example.campaign.protos.TargetOrBuilder getTargetOrBuilder();
}
