// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: campaign.proto
// Protobuf Java Version: 4.27.2

package com.example.campaign.protos;

public final class CampaignProtos {
  private CampaignProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      CampaignProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_campaign_RuleExpr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_campaign_RuleExpr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_campaign_RuleNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_campaign_RuleNode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_campaign_RuleOpExpr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_campaign_RuleOpExpr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_campaign_Rule_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_campaign_Rule_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_campaign_Schedule_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_campaign_Schedule_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_campaign_Target_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_campaign_Target_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_campaign_Campaign_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_campaign_Campaign_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016campaign.proto\022\010campaign\"d\n\010RuleExpr\022\'" +
      "\n\trule_node\030\001 \001(\0132\022.campaign.RuleNodeH\000\022" +
      "\'\n\007rule_op\030\002 \001(\0132\024.campaign.RuleOpExprH\000" +
      "B\006\n\004expr\"A\n\010RuleNode\022 \n\004type\030\001 \001(\0162\022.cam" +
      "paign.RuleType\022\023\n\013description\030\002 \001(\t\"o\n\nR" +
      "uleOpExpr\022\034\n\002op\030\001 \001(\0162\020.campaign.RuleOp\022" +
      " \n\004left\030\002 \001(\0132\022.campaign.RuleExpr\022!\n\005rig" +
      "ht\030\003 \001(\0132\022.campaign.RuleExpr\"(\n\004Rule\022 \n\004" +
      "expr\030\001 \001(\0132\022.campaign.RuleExpr\">\n\010Schedu" +
      "le\"2\n\014ScheduleType\022\t\n\005DAILY\020\000\022\n\n\006WEEKLY\020" +
      "\001\022\013\n\007MONTHLY\020\002\"S\n\006Target\022\024\n\014notification" +
      "\030\001 \001(\010\022\037\n\027homepage_injected_shelf\030\002 \001(\010\022" +
      "\022\n\nafter_play\030\003 \001(\010\"p\n\010Campaign\022\034\n\004rule\030" +
      "\001 \001(\0132\016.campaign.Rule\022$\n\010schedule\030\002 \001(\0132" +
      "\022.campaign.Schedule\022 \n\006target\030\003 \001(\0132\020.ca" +
      "mpaign.Target*#\n\010RuleType\022\t\n\005BATCH\020\000\022\014\n\010" +
      "REALTIME\020\001*\031\n\006RuleOp\022\007\n\003AND\020\000\022\006\n\002OR\020\001B/\n" +
      "\033com.example.campaign.protosB\016CampaignPr" +
      "otosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_campaign_RuleExpr_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_campaign_RuleExpr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_campaign_RuleExpr_descriptor,
        new java.lang.String[] { "RuleNode", "RuleOp", "Expr", });
    internal_static_campaign_RuleNode_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_campaign_RuleNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_campaign_RuleNode_descriptor,
        new java.lang.String[] { "Type", "Description", });
    internal_static_campaign_RuleOpExpr_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_campaign_RuleOpExpr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_campaign_RuleOpExpr_descriptor,
        new java.lang.String[] { "Op", "Left", "Right", });
    internal_static_campaign_Rule_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_campaign_Rule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_campaign_Rule_descriptor,
        new java.lang.String[] { "Expr", });
    internal_static_campaign_Schedule_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_campaign_Schedule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_campaign_Schedule_descriptor,
        new java.lang.String[] { });
    internal_static_campaign_Target_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_campaign_Target_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_campaign_Target_descriptor,
        new java.lang.String[] { "Notification", "HomepageInjectedShelf", "AfterPlay", });
    internal_static_campaign_Campaign_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_campaign_Campaign_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_campaign_Campaign_descriptor,
        new java.lang.String[] { "Rule", "Schedule", "Target", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
