// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: campaign.proto
// Protobuf Java Version: 4.27.2

package com.example.campaign.protos;

public interface RuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:campaign.Rule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.campaign.RuleExpr expr = 1;</code>
   * @return Whether the expr field is set.
   */
  boolean hasExpr();
  /**
   * <code>.campaign.RuleExpr expr = 1;</code>
   * @return The expr.
   */
  com.example.campaign.protos.RuleExpr getExpr();
  /**
   * <code>.campaign.RuleExpr expr = 1;</code>
   */
  com.example.campaign.protos.RuleExprOrBuilder getExprOrBuilder();
}
