// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: campaign.proto
// Protobuf Java Version: 4.27.2

package com.example.campaign.protos;

/**
 * Protobuf type {@code campaign.RuleOpExpr}
 */
public final class RuleOpExpr extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:campaign.RuleOpExpr)
    RuleOpExprOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      RuleOpExpr.class.getName());
  }
  // Use RuleOpExpr.newBuilder() to construct.
  private RuleOpExpr(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RuleOpExpr() {
    op_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.campaign.protos.CampaignProtos.internal_static_campaign_RuleOpExpr_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.campaign.protos.CampaignProtos.internal_static_campaign_RuleOpExpr_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.campaign.protos.RuleOpExpr.class, com.example.campaign.protos.RuleOpExpr.Builder.class);
  }

  private int bitField0_;
  public static final int OP_FIELD_NUMBER = 1;
  private int op_ = 0;
  /**
   * <code>.campaign.RuleOp op = 1;</code>
   * @return The enum numeric value on the wire for op.
   */
  @java.lang.Override public int getOpValue() {
    return op_;
  }
  /**
   * <code>.campaign.RuleOp op = 1;</code>
   * @return The op.
   */
  @java.lang.Override public com.example.campaign.protos.RuleOp getOp() {
    com.example.campaign.protos.RuleOp result = com.example.campaign.protos.RuleOp.forNumber(op_);
    return result == null ? com.example.campaign.protos.RuleOp.UNRECOGNIZED : result;
  }

  public static final int LEFT_FIELD_NUMBER = 2;
  private com.example.campaign.protos.RuleExpr left_;
  /**
   * <code>.campaign.RuleExpr left = 2;</code>
   * @return Whether the left field is set.
   */
  @java.lang.Override
  public boolean hasLeft() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.campaign.RuleExpr left = 2;</code>
   * @return The left.
   */
  @java.lang.Override
  public com.example.campaign.protos.RuleExpr getLeft() {
    return left_ == null ? com.example.campaign.protos.RuleExpr.getDefaultInstance() : left_;
  }
  /**
   * <code>.campaign.RuleExpr left = 2;</code>
   */
  @java.lang.Override
  public com.example.campaign.protos.RuleExprOrBuilder getLeftOrBuilder() {
    return left_ == null ? com.example.campaign.protos.RuleExpr.getDefaultInstance() : left_;
  }

  public static final int RIGHT_FIELD_NUMBER = 3;
  private com.example.campaign.protos.RuleExpr right_;
  /**
   * <code>.campaign.RuleExpr right = 3;</code>
   * @return Whether the right field is set.
   */
  @java.lang.Override
  public boolean hasRight() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.campaign.RuleExpr right = 3;</code>
   * @return The right.
   */
  @java.lang.Override
  public com.example.campaign.protos.RuleExpr getRight() {
    return right_ == null ? com.example.campaign.protos.RuleExpr.getDefaultInstance() : right_;
  }
  /**
   * <code>.campaign.RuleExpr right = 3;</code>
   */
  @java.lang.Override
  public com.example.campaign.protos.RuleExprOrBuilder getRightOrBuilder() {
    return right_ == null ? com.example.campaign.protos.RuleExpr.getDefaultInstance() : right_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (op_ != com.example.campaign.protos.RuleOp.AND.getNumber()) {
      output.writeEnum(1, op_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getLeft());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getRight());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (op_ != com.example.campaign.protos.RuleOp.AND.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, op_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLeft());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRight());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.campaign.protos.RuleOpExpr)) {
      return super.equals(obj);
    }
    com.example.campaign.protos.RuleOpExpr other = (com.example.campaign.protos.RuleOpExpr) obj;

    if (op_ != other.op_) return false;
    if (hasLeft() != other.hasLeft()) return false;
    if (hasLeft()) {
      if (!getLeft()
          .equals(other.getLeft())) return false;
    }
    if (hasRight() != other.hasRight()) return false;
    if (hasRight()) {
      if (!getRight()
          .equals(other.getRight())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OP_FIELD_NUMBER;
    hash = (53 * hash) + op_;
    if (hasLeft()) {
      hash = (37 * hash) + LEFT_FIELD_NUMBER;
      hash = (53 * hash) + getLeft().hashCode();
    }
    if (hasRight()) {
      hash = (37 * hash) + RIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getRight().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.campaign.protos.RuleOpExpr parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.campaign.protos.RuleOpExpr parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.campaign.protos.RuleOpExpr parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.campaign.protos.RuleOpExpr parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.campaign.protos.RuleOpExpr parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.campaign.protos.RuleOpExpr parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.campaign.protos.RuleOpExpr parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.campaign.protos.RuleOpExpr parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.campaign.protos.RuleOpExpr parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.campaign.protos.RuleOpExpr parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.campaign.protos.RuleOpExpr parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.campaign.protos.RuleOpExpr parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.campaign.protos.RuleOpExpr prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code campaign.RuleOpExpr}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:campaign.RuleOpExpr)
      com.example.campaign.protos.RuleOpExprOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.campaign.protos.CampaignProtos.internal_static_campaign_RuleOpExpr_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.campaign.protos.CampaignProtos.internal_static_campaign_RuleOpExpr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.campaign.protos.RuleOpExpr.class, com.example.campaign.protos.RuleOpExpr.Builder.class);
    }

    // Construct using com.example.campaign.protos.RuleOpExpr.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getLeftFieldBuilder();
        getRightFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      op_ = 0;
      left_ = null;
      if (leftBuilder_ != null) {
        leftBuilder_.dispose();
        leftBuilder_ = null;
      }
      right_ = null;
      if (rightBuilder_ != null) {
        rightBuilder_.dispose();
        rightBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.campaign.protos.CampaignProtos.internal_static_campaign_RuleOpExpr_descriptor;
    }

    @java.lang.Override
    public com.example.campaign.protos.RuleOpExpr getDefaultInstanceForType() {
      return com.example.campaign.protos.RuleOpExpr.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.campaign.protos.RuleOpExpr build() {
      com.example.campaign.protos.RuleOpExpr result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.campaign.protos.RuleOpExpr buildPartial() {
      com.example.campaign.protos.RuleOpExpr result = new com.example.campaign.protos.RuleOpExpr(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.campaign.protos.RuleOpExpr result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.op_ = op_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.left_ = leftBuilder_ == null
            ? left_
            : leftBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.right_ = rightBuilder_ == null
            ? right_
            : rightBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.campaign.protos.RuleOpExpr) {
        return mergeFrom((com.example.campaign.protos.RuleOpExpr)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.campaign.protos.RuleOpExpr other) {
      if (other == com.example.campaign.protos.RuleOpExpr.getDefaultInstance()) return this;
      if (other.op_ != 0) {
        setOpValue(other.getOpValue());
      }
      if (other.hasLeft()) {
        mergeLeft(other.getLeft());
      }
      if (other.hasRight()) {
        mergeRight(other.getRight());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              op_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getLeftFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getRightFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int op_ = 0;
    /**
     * <code>.campaign.RuleOp op = 1;</code>
     * @return The enum numeric value on the wire for op.
     */
    @java.lang.Override public int getOpValue() {
      return op_;
    }
    /**
     * <code>.campaign.RuleOp op = 1;</code>
     * @param value The enum numeric value on the wire for op to set.
     * @return This builder for chaining.
     */
    public Builder setOpValue(int value) {
      op_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.RuleOp op = 1;</code>
     * @return The op.
     */
    @java.lang.Override
    public com.example.campaign.protos.RuleOp getOp() {
      com.example.campaign.protos.RuleOp result = com.example.campaign.protos.RuleOp.forNumber(op_);
      return result == null ? com.example.campaign.protos.RuleOp.UNRECOGNIZED : result;
    }
    /**
     * <code>.campaign.RuleOp op = 1;</code>
     * @param value The op to set.
     * @return This builder for chaining.
     */
    public Builder setOp(com.example.campaign.protos.RuleOp value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      op_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.RuleOp op = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      op_ = 0;
      onChanged();
      return this;
    }

    private com.example.campaign.protos.RuleExpr left_;
    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.RuleExpr, com.example.campaign.protos.RuleExpr.Builder, com.example.campaign.protos.RuleExprOrBuilder> leftBuilder_;
    /**
     * <code>.campaign.RuleExpr left = 2;</code>
     * @return Whether the left field is set.
     */
    public boolean hasLeft() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.campaign.RuleExpr left = 2;</code>
     * @return The left.
     */
    public com.example.campaign.protos.RuleExpr getLeft() {
      if (leftBuilder_ == null) {
        return left_ == null ? com.example.campaign.protos.RuleExpr.getDefaultInstance() : left_;
      } else {
        return leftBuilder_.getMessage();
      }
    }
    /**
     * <code>.campaign.RuleExpr left = 2;</code>
     */
    public Builder setLeft(com.example.campaign.protos.RuleExpr value) {
      if (leftBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        left_ = value;
      } else {
        leftBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.RuleExpr left = 2;</code>
     */
    public Builder setLeft(
        com.example.campaign.protos.RuleExpr.Builder builderForValue) {
      if (leftBuilder_ == null) {
        left_ = builderForValue.build();
      } else {
        leftBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.RuleExpr left = 2;</code>
     */
    public Builder mergeLeft(com.example.campaign.protos.RuleExpr value) {
      if (leftBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          left_ != null &&
          left_ != com.example.campaign.protos.RuleExpr.getDefaultInstance()) {
          getLeftBuilder().mergeFrom(value);
        } else {
          left_ = value;
        }
      } else {
        leftBuilder_.mergeFrom(value);
      }
      if (left_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.campaign.RuleExpr left = 2;</code>
     */
    public Builder clearLeft() {
      bitField0_ = (bitField0_ & ~0x00000002);
      left_ = null;
      if (leftBuilder_ != null) {
        leftBuilder_.dispose();
        leftBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.RuleExpr left = 2;</code>
     */
    public com.example.campaign.protos.RuleExpr.Builder getLeftBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getLeftFieldBuilder().getBuilder();
    }
    /**
     * <code>.campaign.RuleExpr left = 2;</code>
     */
    public com.example.campaign.protos.RuleExprOrBuilder getLeftOrBuilder() {
      if (leftBuilder_ != null) {
        return leftBuilder_.getMessageOrBuilder();
      } else {
        return left_ == null ?
            com.example.campaign.protos.RuleExpr.getDefaultInstance() : left_;
      }
    }
    /**
     * <code>.campaign.RuleExpr left = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.RuleExpr, com.example.campaign.protos.RuleExpr.Builder, com.example.campaign.protos.RuleExprOrBuilder> 
        getLeftFieldBuilder() {
      if (leftBuilder_ == null) {
        leftBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.campaign.protos.RuleExpr, com.example.campaign.protos.RuleExpr.Builder, com.example.campaign.protos.RuleExprOrBuilder>(
                getLeft(),
                getParentForChildren(),
                isClean());
        left_ = null;
      }
      return leftBuilder_;
    }

    private com.example.campaign.protos.RuleExpr right_;
    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.RuleExpr, com.example.campaign.protos.RuleExpr.Builder, com.example.campaign.protos.RuleExprOrBuilder> rightBuilder_;
    /**
     * <code>.campaign.RuleExpr right = 3;</code>
     * @return Whether the right field is set.
     */
    public boolean hasRight() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.campaign.RuleExpr right = 3;</code>
     * @return The right.
     */
    public com.example.campaign.protos.RuleExpr getRight() {
      if (rightBuilder_ == null) {
        return right_ == null ? com.example.campaign.protos.RuleExpr.getDefaultInstance() : right_;
      } else {
        return rightBuilder_.getMessage();
      }
    }
    /**
     * <code>.campaign.RuleExpr right = 3;</code>
     */
    public Builder setRight(com.example.campaign.protos.RuleExpr value) {
      if (rightBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        right_ = value;
      } else {
        rightBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.RuleExpr right = 3;</code>
     */
    public Builder setRight(
        com.example.campaign.protos.RuleExpr.Builder builderForValue) {
      if (rightBuilder_ == null) {
        right_ = builderForValue.build();
      } else {
        rightBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.RuleExpr right = 3;</code>
     */
    public Builder mergeRight(com.example.campaign.protos.RuleExpr value) {
      if (rightBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          right_ != null &&
          right_ != com.example.campaign.protos.RuleExpr.getDefaultInstance()) {
          getRightBuilder().mergeFrom(value);
        } else {
          right_ = value;
        }
      } else {
        rightBuilder_.mergeFrom(value);
      }
      if (right_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.campaign.RuleExpr right = 3;</code>
     */
    public Builder clearRight() {
      bitField0_ = (bitField0_ & ~0x00000004);
      right_ = null;
      if (rightBuilder_ != null) {
        rightBuilder_.dispose();
        rightBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.campaign.RuleExpr right = 3;</code>
     */
    public com.example.campaign.protos.RuleExpr.Builder getRightBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getRightFieldBuilder().getBuilder();
    }
    /**
     * <code>.campaign.RuleExpr right = 3;</code>
     */
    public com.example.campaign.protos.RuleExprOrBuilder getRightOrBuilder() {
      if (rightBuilder_ != null) {
        return rightBuilder_.getMessageOrBuilder();
      } else {
        return right_ == null ?
            com.example.campaign.protos.RuleExpr.getDefaultInstance() : right_;
      }
    }
    /**
     * <code>.campaign.RuleExpr right = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.RuleExpr, com.example.campaign.protos.RuleExpr.Builder, com.example.campaign.protos.RuleExprOrBuilder> 
        getRightFieldBuilder() {
      if (rightBuilder_ == null) {
        rightBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.campaign.protos.RuleExpr, com.example.campaign.protos.RuleExpr.Builder, com.example.campaign.protos.RuleExprOrBuilder>(
                getRight(),
                getParentForChildren(),
                isClean());
        right_ = null;
      }
      return rightBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:campaign.RuleOpExpr)
  }

  // @@protoc_insertion_point(class_scope:campaign.RuleOpExpr)
  private static final com.example.campaign.protos.RuleOpExpr DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.campaign.protos.RuleOpExpr();
  }

  public static com.example.campaign.protos.RuleOpExpr getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RuleOpExpr>
      PARSER = new com.google.protobuf.AbstractParser<RuleOpExpr>() {
    @java.lang.Override
    public RuleOpExpr parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RuleOpExpr> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RuleOpExpr> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.campaign.protos.RuleOpExpr getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

