// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: campaign.proto
// Protobuf Java Version: 4.27.2

package com.example.campaign.protos;

/**
 * Protobuf type {@code campaign.RuleExpr}
 */
public final class RuleExpr extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:campaign.RuleExpr)
    RuleExprOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      RuleExpr.class.getName());
  }
  // Use RuleExpr.newBuilder() to construct.
  private RuleExpr(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RuleExpr() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.campaign.protos.CampaignProtos.internal_static_campaign_RuleExpr_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.campaign.protos.CampaignProtos.internal_static_campaign_RuleExpr_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.campaign.protos.RuleExpr.class, com.example.campaign.protos.RuleExpr.Builder.class);
  }

  private int exprCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object expr_;
  public enum ExprCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    RULE_NODE(1),
    RULE_OP(2),
    EXPR_NOT_SET(0);
    private final int value;
    private ExprCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ExprCase valueOf(int value) {
      return forNumber(value);
    }

    public static ExprCase forNumber(int value) {
      switch (value) {
        case 1: return RULE_NODE;
        case 2: return RULE_OP;
        case 0: return EXPR_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ExprCase
  getExprCase() {
    return ExprCase.forNumber(
        exprCase_);
  }

  public static final int RULE_NODE_FIELD_NUMBER = 1;
  /**
   * <code>.campaign.RuleNode rule_node = 1;</code>
   * @return Whether the ruleNode field is set.
   */
  @java.lang.Override
  public boolean hasRuleNode() {
    return exprCase_ == 1;
  }
  /**
   * <code>.campaign.RuleNode rule_node = 1;</code>
   * @return The ruleNode.
   */
  @java.lang.Override
  public com.example.campaign.protos.RuleNode getRuleNode() {
    if (exprCase_ == 1) {
       return (com.example.campaign.protos.RuleNode) expr_;
    }
    return com.example.campaign.protos.RuleNode.getDefaultInstance();
  }
  /**
   * <code>.campaign.RuleNode rule_node = 1;</code>
   */
  @java.lang.Override
  public com.example.campaign.protos.RuleNodeOrBuilder getRuleNodeOrBuilder() {
    if (exprCase_ == 1) {
       return (com.example.campaign.protos.RuleNode) expr_;
    }
    return com.example.campaign.protos.RuleNode.getDefaultInstance();
  }

  public static final int RULE_OP_FIELD_NUMBER = 2;
  /**
   * <code>.campaign.RuleOpExpr rule_op = 2;</code>
   * @return Whether the ruleOp field is set.
   */
  @java.lang.Override
  public boolean hasRuleOp() {
    return exprCase_ == 2;
  }
  /**
   * <code>.campaign.RuleOpExpr rule_op = 2;</code>
   * @return The ruleOp.
   */
  @java.lang.Override
  public com.example.campaign.protos.RuleOpExpr getRuleOp() {
    if (exprCase_ == 2) {
       return (com.example.campaign.protos.RuleOpExpr) expr_;
    }
    return com.example.campaign.protos.RuleOpExpr.getDefaultInstance();
  }
  /**
   * <code>.campaign.RuleOpExpr rule_op = 2;</code>
   */
  @java.lang.Override
  public com.example.campaign.protos.RuleOpExprOrBuilder getRuleOpOrBuilder() {
    if (exprCase_ == 2) {
       return (com.example.campaign.protos.RuleOpExpr) expr_;
    }
    return com.example.campaign.protos.RuleOpExpr.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (exprCase_ == 1) {
      output.writeMessage(1, (com.example.campaign.protos.RuleNode) expr_);
    }
    if (exprCase_ == 2) {
      output.writeMessage(2, (com.example.campaign.protos.RuleOpExpr) expr_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (exprCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.example.campaign.protos.RuleNode) expr_);
    }
    if (exprCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.example.campaign.protos.RuleOpExpr) expr_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.campaign.protos.RuleExpr)) {
      return super.equals(obj);
    }
    com.example.campaign.protos.RuleExpr other = (com.example.campaign.protos.RuleExpr) obj;

    if (!getExprCase().equals(other.getExprCase())) return false;
    switch (exprCase_) {
      case 1:
        if (!getRuleNode()
            .equals(other.getRuleNode())) return false;
        break;
      case 2:
        if (!getRuleOp()
            .equals(other.getRuleOp())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (exprCase_) {
      case 1:
        hash = (37 * hash) + RULE_NODE_FIELD_NUMBER;
        hash = (53 * hash) + getRuleNode().hashCode();
        break;
      case 2:
        hash = (37 * hash) + RULE_OP_FIELD_NUMBER;
        hash = (53 * hash) + getRuleOp().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.campaign.protos.RuleExpr parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.campaign.protos.RuleExpr parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.campaign.protos.RuleExpr parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.campaign.protos.RuleExpr parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.campaign.protos.RuleExpr parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.campaign.protos.RuleExpr parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.campaign.protos.RuleExpr parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.campaign.protos.RuleExpr parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.campaign.protos.RuleExpr parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.campaign.protos.RuleExpr parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.campaign.protos.RuleExpr parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.campaign.protos.RuleExpr parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.campaign.protos.RuleExpr prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code campaign.RuleExpr}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:campaign.RuleExpr)
      com.example.campaign.protos.RuleExprOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.campaign.protos.CampaignProtos.internal_static_campaign_RuleExpr_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.campaign.protos.CampaignProtos.internal_static_campaign_RuleExpr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.campaign.protos.RuleExpr.class, com.example.campaign.protos.RuleExpr.Builder.class);
    }

    // Construct using com.example.campaign.protos.RuleExpr.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (ruleNodeBuilder_ != null) {
        ruleNodeBuilder_.clear();
      }
      if (ruleOpBuilder_ != null) {
        ruleOpBuilder_.clear();
      }
      exprCase_ = 0;
      expr_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.campaign.protos.CampaignProtos.internal_static_campaign_RuleExpr_descriptor;
    }

    @java.lang.Override
    public com.example.campaign.protos.RuleExpr getDefaultInstanceForType() {
      return com.example.campaign.protos.RuleExpr.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.campaign.protos.RuleExpr build() {
      com.example.campaign.protos.RuleExpr result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.campaign.protos.RuleExpr buildPartial() {
      com.example.campaign.protos.RuleExpr result = new com.example.campaign.protos.RuleExpr(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.campaign.protos.RuleExpr result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.example.campaign.protos.RuleExpr result) {
      result.exprCase_ = exprCase_;
      result.expr_ = this.expr_;
      if (exprCase_ == 1 &&
          ruleNodeBuilder_ != null) {
        result.expr_ = ruleNodeBuilder_.build();
      }
      if (exprCase_ == 2 &&
          ruleOpBuilder_ != null) {
        result.expr_ = ruleOpBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.campaign.protos.RuleExpr) {
        return mergeFrom((com.example.campaign.protos.RuleExpr)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.campaign.protos.RuleExpr other) {
      if (other == com.example.campaign.protos.RuleExpr.getDefaultInstance()) return this;
      switch (other.getExprCase()) {
        case RULE_NODE: {
          mergeRuleNode(other.getRuleNode());
          break;
        }
        case RULE_OP: {
          mergeRuleOp(other.getRuleOp());
          break;
        }
        case EXPR_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getRuleNodeFieldBuilder().getBuilder(),
                  extensionRegistry);
              exprCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getRuleOpFieldBuilder().getBuilder(),
                  extensionRegistry);
              exprCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int exprCase_ = 0;
    private java.lang.Object expr_;
    public ExprCase
        getExprCase() {
      return ExprCase.forNumber(
          exprCase_);
    }

    public Builder clearExpr() {
      exprCase_ = 0;
      expr_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.RuleNode, com.example.campaign.protos.RuleNode.Builder, com.example.campaign.protos.RuleNodeOrBuilder> ruleNodeBuilder_;
    /**
     * <code>.campaign.RuleNode rule_node = 1;</code>
     * @return Whether the ruleNode field is set.
     */
    @java.lang.Override
    public boolean hasRuleNode() {
      return exprCase_ == 1;
    }
    /**
     * <code>.campaign.RuleNode rule_node = 1;</code>
     * @return The ruleNode.
     */
    @java.lang.Override
    public com.example.campaign.protos.RuleNode getRuleNode() {
      if (ruleNodeBuilder_ == null) {
        if (exprCase_ == 1) {
          return (com.example.campaign.protos.RuleNode) expr_;
        }
        return com.example.campaign.protos.RuleNode.getDefaultInstance();
      } else {
        if (exprCase_ == 1) {
          return ruleNodeBuilder_.getMessage();
        }
        return com.example.campaign.protos.RuleNode.getDefaultInstance();
      }
    }
    /**
     * <code>.campaign.RuleNode rule_node = 1;</code>
     */
    public Builder setRuleNode(com.example.campaign.protos.RuleNode value) {
      if (ruleNodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expr_ = value;
        onChanged();
      } else {
        ruleNodeBuilder_.setMessage(value);
      }
      exprCase_ = 1;
      return this;
    }
    /**
     * <code>.campaign.RuleNode rule_node = 1;</code>
     */
    public Builder setRuleNode(
        com.example.campaign.protos.RuleNode.Builder builderForValue) {
      if (ruleNodeBuilder_ == null) {
        expr_ = builderForValue.build();
        onChanged();
      } else {
        ruleNodeBuilder_.setMessage(builderForValue.build());
      }
      exprCase_ = 1;
      return this;
    }
    /**
     * <code>.campaign.RuleNode rule_node = 1;</code>
     */
    public Builder mergeRuleNode(com.example.campaign.protos.RuleNode value) {
      if (ruleNodeBuilder_ == null) {
        if (exprCase_ == 1 &&
            expr_ != com.example.campaign.protos.RuleNode.getDefaultInstance()) {
          expr_ = com.example.campaign.protos.RuleNode.newBuilder((com.example.campaign.protos.RuleNode) expr_)
              .mergeFrom(value).buildPartial();
        } else {
          expr_ = value;
        }
        onChanged();
      } else {
        if (exprCase_ == 1) {
          ruleNodeBuilder_.mergeFrom(value);
        } else {
          ruleNodeBuilder_.setMessage(value);
        }
      }
      exprCase_ = 1;
      return this;
    }
    /**
     * <code>.campaign.RuleNode rule_node = 1;</code>
     */
    public Builder clearRuleNode() {
      if (ruleNodeBuilder_ == null) {
        if (exprCase_ == 1) {
          exprCase_ = 0;
          expr_ = null;
          onChanged();
        }
      } else {
        if (exprCase_ == 1) {
          exprCase_ = 0;
          expr_ = null;
        }
        ruleNodeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.campaign.RuleNode rule_node = 1;</code>
     */
    public com.example.campaign.protos.RuleNode.Builder getRuleNodeBuilder() {
      return getRuleNodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.campaign.RuleNode rule_node = 1;</code>
     */
    @java.lang.Override
    public com.example.campaign.protos.RuleNodeOrBuilder getRuleNodeOrBuilder() {
      if ((exprCase_ == 1) && (ruleNodeBuilder_ != null)) {
        return ruleNodeBuilder_.getMessageOrBuilder();
      } else {
        if (exprCase_ == 1) {
          return (com.example.campaign.protos.RuleNode) expr_;
        }
        return com.example.campaign.protos.RuleNode.getDefaultInstance();
      }
    }
    /**
     * <code>.campaign.RuleNode rule_node = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.RuleNode, com.example.campaign.protos.RuleNode.Builder, com.example.campaign.protos.RuleNodeOrBuilder> 
        getRuleNodeFieldBuilder() {
      if (ruleNodeBuilder_ == null) {
        if (!(exprCase_ == 1)) {
          expr_ = com.example.campaign.protos.RuleNode.getDefaultInstance();
        }
        ruleNodeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.campaign.protos.RuleNode, com.example.campaign.protos.RuleNode.Builder, com.example.campaign.protos.RuleNodeOrBuilder>(
                (com.example.campaign.protos.RuleNode) expr_,
                getParentForChildren(),
                isClean());
        expr_ = null;
      }
      exprCase_ = 1;
      onChanged();
      return ruleNodeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.RuleOpExpr, com.example.campaign.protos.RuleOpExpr.Builder, com.example.campaign.protos.RuleOpExprOrBuilder> ruleOpBuilder_;
    /**
     * <code>.campaign.RuleOpExpr rule_op = 2;</code>
     * @return Whether the ruleOp field is set.
     */
    @java.lang.Override
    public boolean hasRuleOp() {
      return exprCase_ == 2;
    }
    /**
     * <code>.campaign.RuleOpExpr rule_op = 2;</code>
     * @return The ruleOp.
     */
    @java.lang.Override
    public com.example.campaign.protos.RuleOpExpr getRuleOp() {
      if (ruleOpBuilder_ == null) {
        if (exprCase_ == 2) {
          return (com.example.campaign.protos.RuleOpExpr) expr_;
        }
        return com.example.campaign.protos.RuleOpExpr.getDefaultInstance();
      } else {
        if (exprCase_ == 2) {
          return ruleOpBuilder_.getMessage();
        }
        return com.example.campaign.protos.RuleOpExpr.getDefaultInstance();
      }
    }
    /**
     * <code>.campaign.RuleOpExpr rule_op = 2;</code>
     */
    public Builder setRuleOp(com.example.campaign.protos.RuleOpExpr value) {
      if (ruleOpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expr_ = value;
        onChanged();
      } else {
        ruleOpBuilder_.setMessage(value);
      }
      exprCase_ = 2;
      return this;
    }
    /**
     * <code>.campaign.RuleOpExpr rule_op = 2;</code>
     */
    public Builder setRuleOp(
        com.example.campaign.protos.RuleOpExpr.Builder builderForValue) {
      if (ruleOpBuilder_ == null) {
        expr_ = builderForValue.build();
        onChanged();
      } else {
        ruleOpBuilder_.setMessage(builderForValue.build());
      }
      exprCase_ = 2;
      return this;
    }
    /**
     * <code>.campaign.RuleOpExpr rule_op = 2;</code>
     */
    public Builder mergeRuleOp(com.example.campaign.protos.RuleOpExpr value) {
      if (ruleOpBuilder_ == null) {
        if (exprCase_ == 2 &&
            expr_ != com.example.campaign.protos.RuleOpExpr.getDefaultInstance()) {
          expr_ = com.example.campaign.protos.RuleOpExpr.newBuilder((com.example.campaign.protos.RuleOpExpr) expr_)
              .mergeFrom(value).buildPartial();
        } else {
          expr_ = value;
        }
        onChanged();
      } else {
        if (exprCase_ == 2) {
          ruleOpBuilder_.mergeFrom(value);
        } else {
          ruleOpBuilder_.setMessage(value);
        }
      }
      exprCase_ = 2;
      return this;
    }
    /**
     * <code>.campaign.RuleOpExpr rule_op = 2;</code>
     */
    public Builder clearRuleOp() {
      if (ruleOpBuilder_ == null) {
        if (exprCase_ == 2) {
          exprCase_ = 0;
          expr_ = null;
          onChanged();
        }
      } else {
        if (exprCase_ == 2) {
          exprCase_ = 0;
          expr_ = null;
        }
        ruleOpBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.campaign.RuleOpExpr rule_op = 2;</code>
     */
    public com.example.campaign.protos.RuleOpExpr.Builder getRuleOpBuilder() {
      return getRuleOpFieldBuilder().getBuilder();
    }
    /**
     * <code>.campaign.RuleOpExpr rule_op = 2;</code>
     */
    @java.lang.Override
    public com.example.campaign.protos.RuleOpExprOrBuilder getRuleOpOrBuilder() {
      if ((exprCase_ == 2) && (ruleOpBuilder_ != null)) {
        return ruleOpBuilder_.getMessageOrBuilder();
      } else {
        if (exprCase_ == 2) {
          return (com.example.campaign.protos.RuleOpExpr) expr_;
        }
        return com.example.campaign.protos.RuleOpExpr.getDefaultInstance();
      }
    }
    /**
     * <code>.campaign.RuleOpExpr rule_op = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.example.campaign.protos.RuleOpExpr, com.example.campaign.protos.RuleOpExpr.Builder, com.example.campaign.protos.RuleOpExprOrBuilder> 
        getRuleOpFieldBuilder() {
      if (ruleOpBuilder_ == null) {
        if (!(exprCase_ == 2)) {
          expr_ = com.example.campaign.protos.RuleOpExpr.getDefaultInstance();
        }
        ruleOpBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.campaign.protos.RuleOpExpr, com.example.campaign.protos.RuleOpExpr.Builder, com.example.campaign.protos.RuleOpExprOrBuilder>(
                (com.example.campaign.protos.RuleOpExpr) expr_,
                getParentForChildren(),
                isClean());
        expr_ = null;
      }
      exprCase_ = 2;
      onChanged();
      return ruleOpBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:campaign.RuleExpr)
  }

  // @@protoc_insertion_point(class_scope:campaign.RuleExpr)
  private static final com.example.campaign.protos.RuleExpr DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.campaign.protos.RuleExpr();
  }

  public static com.example.campaign.protos.RuleExpr getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RuleExpr>
      PARSER = new com.google.protobuf.AbstractParser<RuleExpr>() {
    @java.lang.Override
    public RuleExpr parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RuleExpr> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RuleExpr> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.campaign.protos.RuleExpr getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

