// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: campaign.proto
// Protobuf Java Version: 4.27.2

package com.example.campaign.protos;

public interface RuleNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:campaign.RuleNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.campaign.RuleType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.campaign.RuleType type = 1;</code>
   * @return The type.
   */
  com.example.campaign.protos.RuleType getType();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
