// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: campaign.proto
// Protobuf Java Version: 4.27.2

package com.example.campaign.protos;

public interface RuleOpExprOrBuilder extends
    // @@protoc_insertion_point(interface_extends:campaign.RuleOpExpr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.campaign.RuleOp op = 1;</code>
   * @return The enum numeric value on the wire for op.
   */
  int getOpValue();
  /**
   * <code>.campaign.RuleOp op = 1;</code>
   * @return The op.
   */
  com.example.campaign.protos.RuleOp getOp();

  /**
   * <code>.campaign.RuleExpr left = 2;</code>
   * @return Whether the left field is set.
   */
  boolean hasLeft();
  /**
   * <code>.campaign.RuleExpr left = 2;</code>
   * @return The left.
   */
  com.example.campaign.protos.RuleExpr getLeft();
  /**
   * <code>.campaign.RuleExpr left = 2;</code>
   */
  com.example.campaign.protos.RuleExprOrBuilder getLeftOrBuilder();

  /**
   * <code>.campaign.RuleExpr right = 3;</code>
   * @return Whether the right field is set.
   */
  boolean hasRight();
  /**
   * <code>.campaign.RuleExpr right = 3;</code>
   * @return The right.
   */
  com.example.campaign.protos.RuleExpr getRight();
  /**
   * <code>.campaign.RuleExpr right = 3;</code>
   */
  com.example.campaign.protos.RuleExprOrBuilder getRightOrBuilder();
}
