// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: campaign.proto
// Protobuf Java Version: 4.27.2

package com.example.campaign.protos;

public interface SubRuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:campaign.SubRule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.campaign.RuleType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.campaign.RuleType type = 1;</code>
   * @return The type.
   */
  com.example.campaign.protos.RuleType getType();

  /**
   * <code>.campaign.Rule rule = 2;</code>
   * @return Whether the rule field is set.
   */
  boolean hasRule();
  /**
   * <code>.campaign.Rule rule = 2;</code>
   * @return The rule.
   */
  com.example.campaign.protos.Rule getRule();
  /**
   * <code>.campaign.Rule rule = 2;</code>
   */
  com.example.campaign.protos.RuleOrBuilder getRuleOrBuilder();
}
