// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: campaign.proto
// Protobuf Java Version: 4.27.2

package com.example.campaign.protos;

public interface TargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:campaign.Target)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool notification = 1;</code>
   * @return The notification.
   */
  boolean getNotification();

  /**
   * <code>bool homepage_injected_shelf = 2;</code>
   * @return The homepageInjectedShelf.
   */
  boolean getHomepageInjectedShelf();

  /**
   * <code>bool after_play = 3;</code>
   * @return The afterPlay.
   */
  boolean getAfterPlay();
}
