// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: campaign.proto
// Protobuf Java Version: 4.27.2

package com.example.campaign.protos;

/**
 * Protobuf type {@code campaign.Target}
 */
public final class Target extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:campaign.Target)
    TargetOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Target.class.getName());
  }
  // Use Target.newBuilder() to construct.
  private Target(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Target() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.campaign.protos.CampaignProtos.internal_static_campaign_Target_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.campaign.protos.CampaignProtos.internal_static_campaign_Target_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.campaign.protos.Target.class, com.example.campaign.protos.Target.Builder.class);
  }

  public static final int NOTIFICATION_FIELD_NUMBER = 1;
  private boolean notification_ = false;
  /**
   * <code>bool notification = 1;</code>
   * @return The notification.
   */
  @java.lang.Override
  public boolean getNotification() {
    return notification_;
  }

  public static final int HOMEPAGE_INJECTED_SHELF_FIELD_NUMBER = 2;
  private boolean homepageInjectedShelf_ = false;
  /**
   * <code>bool homepage_injected_shelf = 2;</code>
   * @return The homepageInjectedShelf.
   */
  @java.lang.Override
  public boolean getHomepageInjectedShelf() {
    return homepageInjectedShelf_;
  }

  public static final int AFTER_PLAY_FIELD_NUMBER = 3;
  private boolean afterPlay_ = false;
  /**
   * <code>bool after_play = 3;</code>
   * @return The afterPlay.
   */
  @java.lang.Override
  public boolean getAfterPlay() {
    return afterPlay_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (notification_ != false) {
      output.writeBool(1, notification_);
    }
    if (homepageInjectedShelf_ != false) {
      output.writeBool(2, homepageInjectedShelf_);
    }
    if (afterPlay_ != false) {
      output.writeBool(3, afterPlay_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (notification_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, notification_);
    }
    if (homepageInjectedShelf_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, homepageInjectedShelf_);
    }
    if (afterPlay_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, afterPlay_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.campaign.protos.Target)) {
      return super.equals(obj);
    }
    com.example.campaign.protos.Target other = (com.example.campaign.protos.Target) obj;

    if (getNotification()
        != other.getNotification()) return false;
    if (getHomepageInjectedShelf()
        != other.getHomepageInjectedShelf()) return false;
    if (getAfterPlay()
        != other.getAfterPlay()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NOTIFICATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNotification());
    hash = (37 * hash) + HOMEPAGE_INJECTED_SHELF_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHomepageInjectedShelf());
    hash = (37 * hash) + AFTER_PLAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAfterPlay());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.campaign.protos.Target parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.campaign.protos.Target parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.campaign.protos.Target parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.campaign.protos.Target parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.campaign.protos.Target parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.campaign.protos.Target parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.campaign.protos.Target parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.campaign.protos.Target parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.campaign.protos.Target parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.campaign.protos.Target parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.campaign.protos.Target parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.campaign.protos.Target parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.campaign.protos.Target prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code campaign.Target}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:campaign.Target)
      com.example.campaign.protos.TargetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.campaign.protos.CampaignProtos.internal_static_campaign_Target_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.campaign.protos.CampaignProtos.internal_static_campaign_Target_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.campaign.protos.Target.class, com.example.campaign.protos.Target.Builder.class);
    }

    // Construct using com.example.campaign.protos.Target.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      notification_ = false;
      homepageInjectedShelf_ = false;
      afterPlay_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.campaign.protos.CampaignProtos.internal_static_campaign_Target_descriptor;
    }

    @java.lang.Override
    public com.example.campaign.protos.Target getDefaultInstanceForType() {
      return com.example.campaign.protos.Target.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.campaign.protos.Target build() {
      com.example.campaign.protos.Target result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.campaign.protos.Target buildPartial() {
      com.example.campaign.protos.Target result = new com.example.campaign.protos.Target(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.campaign.protos.Target result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.notification_ = notification_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.homepageInjectedShelf_ = homepageInjectedShelf_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.afterPlay_ = afterPlay_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.campaign.protos.Target) {
        return mergeFrom((com.example.campaign.protos.Target)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.campaign.protos.Target other) {
      if (other == com.example.campaign.protos.Target.getDefaultInstance()) return this;
      if (other.getNotification() != false) {
        setNotification(other.getNotification());
      }
      if (other.getHomepageInjectedShelf() != false) {
        setHomepageInjectedShelf(other.getHomepageInjectedShelf());
      }
      if (other.getAfterPlay() != false) {
        setAfterPlay(other.getAfterPlay());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              notification_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              homepageInjectedShelf_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              afterPlay_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean notification_ ;
    /**
     * <code>bool notification = 1;</code>
     * @return The notification.
     */
    @java.lang.Override
    public boolean getNotification() {
      return notification_;
    }
    /**
     * <code>bool notification = 1;</code>
     * @param value The notification to set.
     * @return This builder for chaining.
     */
    public Builder setNotification(boolean value) {

      notification_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool notification = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNotification() {
      bitField0_ = (bitField0_ & ~0x00000001);
      notification_ = false;
      onChanged();
      return this;
    }

    private boolean homepageInjectedShelf_ ;
    /**
     * <code>bool homepage_injected_shelf = 2;</code>
     * @return The homepageInjectedShelf.
     */
    @java.lang.Override
    public boolean getHomepageInjectedShelf() {
      return homepageInjectedShelf_;
    }
    /**
     * <code>bool homepage_injected_shelf = 2;</code>
     * @param value The homepageInjectedShelf to set.
     * @return This builder for chaining.
     */
    public Builder setHomepageInjectedShelf(boolean value) {

      homepageInjectedShelf_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool homepage_injected_shelf = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHomepageInjectedShelf() {
      bitField0_ = (bitField0_ & ~0x00000002);
      homepageInjectedShelf_ = false;
      onChanged();
      return this;
    }

    private boolean afterPlay_ ;
    /**
     * <code>bool after_play = 3;</code>
     * @return The afterPlay.
     */
    @java.lang.Override
    public boolean getAfterPlay() {
      return afterPlay_;
    }
    /**
     * <code>bool after_play = 3;</code>
     * @param value The afterPlay to set.
     * @return This builder for chaining.
     */
    public Builder setAfterPlay(boolean value) {

      afterPlay_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool after_play = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAfterPlay() {
      bitField0_ = (bitField0_ & ~0x00000004);
      afterPlay_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:campaign.Target)
  }

  // @@protoc_insertion_point(class_scope:campaign.Target)
  private static final com.example.campaign.protos.Target DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.campaign.protos.Target();
  }

  public static com.example.campaign.protos.Target getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Target>
      PARSER = new com.google.protobuf.AbstractParser<Target>() {
    @java.lang.Override
    public Target parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Target> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Target> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.campaign.protos.Target getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

